name: Mishiev
favicon: null
layout_spectrum: 0.03320501954294741
typography_spectrum: 0.8197804058436304
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
  brandStrength: 0.8207266794051975
  lightness: 0.3271193625405431
  saturation: 0.6545907303225249
  rhythmicContrast: 0.3556646970100701
purpose: []
