name: Mishiev
favicon: null
layout_spectrum: 0.24709
typography_spectrum: 0.2514
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#1d517a'
    - '#f9ffff'
    - '#fb5f36'
    - '#5bb4d3'
    - '#72f975'
  brandStrength: 0
  lightness: 0.375
  saturation: 0
  rhythmicContrast: 0.3556646970100701
purpose: []
