name: Mishiev
favicon: null
layout_spectrum: 0.24709
typography_spectrum: 0.2514
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fff0d0'
    - '#abbbda'
    - '#704637'
    - '#0b090a'
    - '#4d6ead'
  brandStrength: 0
  lightness: 0.375
  saturation: 0
  rhythmicContrast: 0.3556646970100701
purpose: []
