name: Mishiev
favicon: null
layout_spectrum: 0.74917
typography_spectrum: 0.75188
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#7e9188'
    - '#61748c'
    - '#1a5462'
    - '#18394c'
    - '#90aea6'
  brandStrength: 0.5
  lightness: 0.375
  saturation: 0.5
  rhythmicContrast: 0
purpose: []
